package com.geostar.smackandroid.chat.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.geostar.smackandroid.chat.data.dao.ChatRecord;

import com.geostar.smackandroid.chat.data.dao.ChatRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatRecordDaoConfig;

    private final ChatRecordDao chatRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatRecordDaoConfig = daoConfigMap.get(ChatRecordDao.class).clone();
        chatRecordDaoConfig.initIdentityScope(type);

        chatRecordDao = new ChatRecordDao(chatRecordDaoConfig, this);

        registerDao(ChatRecord.class, chatRecordDao);
    }
    
    public void clear() {
        chatRecordDaoConfig.getIdentityScope().clear();
    }

    public ChatRecordDao getChatRecordDao() {
        return chatRecordDao;
    }

}
