package com.geostar.smackandroid.message.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "chat_message_table".
 */
public class ChatMessage implements java.io.Serializable {

    private Long id;
    private String from;
    private String to;
    private Long time;
    private String type;
    private Boolean isRead;
    private String subject;
    private String body;
    private String thread;
    private String extentedContent;
    private Long serverTime;

    public ChatMessage() {
    }

    public ChatMessage(Long id) {
        this.id = id;
    }

    public ChatMessage(Long id, String from, String to, Long time, String type, Boolean isRead, String subject, String body, String thread, String extentedContent, Long serverTime) {
        this.id = id;
        this.from = from;
        this.to = to;
        this.time = time;
        this.type = type;
        this.isRead = isRead;
        this.subject = subject;
        this.body = body;
        this.thread = thread;
        this.extentedContent = extentedContent;
        this.serverTime = serverTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /** 
 	*可选主题 
 	*/
    public String getSubject() {
        return subject;
    }

    /** 
 	*可选主题 
 	*/
    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getThread() {
        return thread;
    }

    public void setThread(String thread) {
        this.thread = thread;
    }

    /** 
 	*额外标签内容，未做解析 
 	*/
    public String getExtentedContent() {
        return extentedContent;
    }

    /** 
 	*额外标签内容，未做解析 
 	*/
    public void setExtentedContent(String extentedContent) {
        this.extentedContent = extentedContent;
    }

    public Long getServerTime() {
        return serverTime;
    }

    public void setServerTime(Long serverTime) {
        this.serverTime = serverTime;
    }

}
