package com.geostar.smackandroid.chat.data.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "chat_record_table".
 */
public class ChatRecord implements java.io.Serializable {

    private Long id;
    private String identify;
    private String chatOjbects;
    private String type;
    private String name;
    private String chatRecordDBPath;

    public ChatRecord() {
    }

    public ChatRecord(Long id) {
        this.id = id;
    }

    public ChatRecord(Long id, String identify, String chatOjbects, String type, String name, String chatRecordDBPath) {
        this.id = id;
        this.identify = identify;
        this.chatOjbects = chatOjbects;
        this.type = type;
        this.name = name;
        this.chatRecordDBPath = chatRecordDBPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentify() {
        return identify;
    }

    public void setIdentify(String identify) {
        this.identify = identify;
    }

    public String getChatOjbects() {
        return chatOjbects;
    }

    public void setChatOjbects(String chatOjbects) {
        this.chatOjbects = chatOjbects;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** 
 	*聊天记录数据库文件路径 
 	*/
    public String getChatRecordDBPath() {
        return chatRecordDBPath;
    }

    /** 
 	*聊天记录数据库文件路径 
 	*/
    public void setChatRecordDBPath(String chatRecordDBPath) {
        this.chatRecordDBPath = chatRecordDBPath;
    }

}
